version: "3"
services:
  app_hc:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app_hc
    restart: unless-stopped
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker/php/app.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - dev

  #Nginx Service
  web_hc:
    image: nginx:alpine
    container_name: web_hc
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev


  postgresql-master:
#    image: docker.io/bitnami/postgresql:12
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - 'dbdatahc:/bitnami/postgresql'
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=passworddev2022
      - POSTGRES_DATABASE=hc
      # - ALLOW_EMPTY_PASSWORD=yes
    networks: 
      - dev

networks:
   dev:

volumes:
  dbdatahc:
    driver: local
